spring:
  application:
    name: back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/it_job_system?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456

server:
  port: 8080